#!/usr/bin/env bash
#installing and configuring nginx
sudo apt-get update
sudo apt-get install -y nginx
sudo service nginx restart
sudo echo "Hello World!" | sudo tee /var/www/html/index.html
sudo service nginx restart
