#!/usr/bin/env bash
# Setting up server to curl port 80 with no issues

#remove the default Nginx configuration
rm /etc/nginx/sites-enabled/default
ln -s etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
#restart nginx
service nginx restart
