#!/usr/bin/env bash
#disable the SIGTERM
terminate() {
    echo "I am invincible!!!"
    exit 0
}
#disable an endless loop
trap terminate SIGTERM
i=0
while [ "$i" -lt 5 ]; do
    echo "To infinity and beyond"
    sleep 2
done
