#!/usr/bin/env bash
#disable the SIGTERM
handle()
{
	echo "I am invincible!!!"
}
trap handle SIGTERM
#display an endless loop
i=0
while [ $i -lt 5 ];
do
        echo "To infinity and beyond"
        sleep 2
	((i++))
done
